### ISSUE TITLE
Accounting Software for Your Cleaning Business: VIDEO & WRITTEN

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#41]
[Video Guidelines](https://github.com/Taskbird/creator-community/blob/main/Video%20Guidelines.pdf)

Email [Community@Taskbird.com](mailto:Community@Taskbird.com) you submissions and questions OR comment below

If you're new here read [How it works](https://github.com/Taskbird/creator-community/blob/main/How%20It%20Works.md) to take the right steps

**Comment by Mr254Kenya** [comment]
Hello @SamHoffer I request your permission to handle this blog post. Attached is the general outline of how I plan to approach the subject. Regards
[Draft Outline-Accounting Software for Your Cleaning Business_ WRITTEN.docx](https://github.com/Taskbird/creator-community/files/8467164/Draft.Outline-Accounting.Software.for.Your.Cleaning.Business_.WRITTEN.docx)

**Comment by Mr254Kenya** [comment]
Hello, sir @SamHoffer Hope you are well. I submitted my final draft for this task about three months ago, but I have not yet received feedback. Also, there is another outline you had approved, but I haven't worked on it because I thought we needed to move one task at a time.
Looking forward to hearing from you. Regards
